services:
  - type: web
    name: vobi-api
    runtime: python
    rootDir: pipeline
    buildCommand: pip install -r requirements.render.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AVAILITY_CLIENT_ID
        sync: false
      - key: AVAILITY_CLIENT_SECRET
        sync: false
